// platform/client/src/lib/ImageContainer.svelte
<script>
    import { onMount } from "svelte";
    
    export let group = "8";
    export let source = "web";

    let images = [];

    $: group && load_images();

    function load_images() {
        fetch("/api/get-group-images", {
            method: "post",
            headers: {
                Accept: "application/json",
                "Content-Type": "application/json",
            },
            body: JSON.stringify({ group: group }),
        })
            .then((res) => res.json())
            .then((data) => {
                images = data[source];
            });
    }

    onMount(() => {
        load_images();
    });
</script>

<div class="image_holder">
    {#each images as im}
        <div class="image">
            <img src={"/images/" + im} alt="source" />
        </div>
    {/each}
</div>

<style>
    .image {
        max-height: 400px;
        margin: 1rem;
        width: fit-content;
    }

    .image img {
        max-height: 100%;
    }

    .image_holder {
        display: flex;
        flex-direction: row;
        overflow-y: scroll;
        max-width: 80vw;
        height: 450px;
        border: 1px solid white;
    }
</style>

// platform/client/src/lib/ImageContainer/ImageContainer.tsx
import { Component, ReactNode } from "react";
import './ImageContainer.css'

export interface ImageContainerProps {
    selectedGroup: string;
    source: string;
}

export interface ImageContainerState {
    images: string[];
    selectedImage?: string;
}

export default class ImageContainer extends Component<ImageContainerProps, ImageContainerState> {
    constructor(props: ImageContainerProps) {
        super(props);
        this.state = {
            images: [] 
        };
    }

    async get_images() {
        let images:string[] = [];
        await fetch("/api/get-group-images", {
            method: "post",
            headers: {
                Accept: "application/json",
                "Content-Type": "application/json",
            },
            body: JSON.stringify({ group: this.props.selectedGroup }),
        })
            .then((res) => res.json())
            .then((data) => {
                images = data[this.props.source];
            });
        console.log(images);
        return images;
    }

    async componentDidMount() {
        const images = await this.get_images();
        this.setState({images: images});
    }

    async componentDidUpdate(prevProps: ImageContainerProps) {
        if (prevProps.selectedGroup !== this.props.selectedGroup) {
            console.log(`Group changed from ${prevProps.selectedGroup} to ${this.props.selectedGroup}`);
            const images = await this.get_images();
            this.setState({images: images});
        }
    }

    render(): ReactNode {
        return (
            <>
                <div className="image-container">
                    {this.state.images.sort().map((image) => (
                        <div className="image">
                            <img src={"/images/" + image} alt="source" />
                        </div>
                    ))}
                </div>
            </>
        )
    }
}
